Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: Flowpack.Website:Document.Default.Template
        suffix: .Template

Neos:
  Fusion:
    defaultContext:
      'Flowpack.Website.GitHub': 'Flowpack\Website\Eel\Helper\GitHubHelper'

Flowpack:
  Website:
    github:
      token: '93d705355708b03aa7c91cbd123c0214e20d5845'
